name: Go Build and Test

on:
  workflow_call:
    inputs:
      go-enabled:
        default: false
        required: false
        type: boolean
      go-build-pattern:
        required: false
        type: string
      go-test-pattern:
        default: './...'
        required: false
        type: string
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-go:
    if: ${{ inputs.go-enabled }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Download Dependencies
        run: go mod download

      - name: Build Project
        if: ${{ inputs.go-build-pattern != '' }}
        run: go build ${{ inputs.go-build-pattern }}

      - name: Run Tests
        if: ${{ inputs.go-test-pattern != '' }}
        run: go test -v ${{ inputs.go-test-pattern }}
